// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl3H7J1rricu_n5_8IcghzWJkGVR8mofs',
    appId: '1:463907809306:web:c8d22ed0c2a181438449a3',
    messagingSenderId: '463907809306',
    projectId: 'jobs-21d4f',
    authDomain: 'jobs-21d4f.firebaseapp.com',
    storageBucket: 'jobs-21d4f.appspot.com',
    measurementId: 'G-J2XHYC31CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzBFXxCoFPcE1HaHdXsWUzvMDYCuDPTPw',
    appId: '1:463907809306:android:5fa8efab99deb26a8449a3',
    messagingSenderId: '463907809306',
    projectId: 'jobs-21d4f',
    storageBucket: 'jobs-21d4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpOKVWErbssRLk-5RqTPiIrABVoFdVGrA',
    appId: '1:463907809306:ios:6edf2aaf0dfe89378449a3',
    messagingSenderId: '463907809306',
    projectId: 'jobs-21d4f',
    storageBucket: 'jobs-21d4f.appspot.com',
    iosClientId: '463907809306-kjq5p51e13clakeqi9st5u1a05u0cd9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.openVacancies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpOKVWErbssRLk-5RqTPiIrABVoFdVGrA',
    appId: '1:463907809306:ios:6edf2aaf0dfe89378449a3',
    messagingSenderId: '463907809306',
    projectId: 'jobs-21d4f',
    storageBucket: 'jobs-21d4f.appspot.com',
    iosClientId: '463907809306-kjq5p51e13clakeqi9st5u1a05u0cd9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.openVacancies',
  );
}
